
# Interactive visualization of the Koeln shallow water flooding simulation
# Requires simulation_data.jld2 (generated by elixir_shallowwater_wave_runup_flood.jl)
using Revise
using GLMakie, JLD2, Statistics
using RayMakie, Lava, Hikari
using GeometryBasics

# Load pre-extracted simulation data
data = load(joinpath(@__DIR__, "simulation_data.jld2"))

x_raw = Float64.(data["x_nodes"])
y_raw = Float64.(data["y_nodes"])
b_raw = Float64.(data["b_nodes"])
terrain_faces = data["global_tri"]

wx_raw = Float64.(data["wet_x"])
wy_raw = Float64.(data["wet_y"])
wb_raw = Float64.(data["wet_b"])
water_faces = data["all_faces"]
water_h_raw = Float64.(data["water_h_frames"])
n_water = data["n_water_nodes"]

times = data["times"]
n_frames = length(times)

# Normalize scene to ~100x100 units centered at origin.
# The raw coordinates are in ETRS89 (x~356000, y~5.644e6) which destroys
# Float32 precision in the raytracer (eps(Float32(5.645e6)) = 0.5 meters!).
x_center, y_center = mean(x_raw), mean(y_raw)
z_center = mean(b_raw)
scene_scale = 100.0 / max(maximum(x_raw) - minimum(x_raw),
    maximum(y_raw) - minimum(y_raw))

norm_x(x) = Float32((x - x_center) * scene_scale)
norm_y(y) = Float32((y - y_center) * scene_scale)
norm_z(z) = Float32((z - z_center) * scene_scale)

x_nodes = norm_x.(x_raw)
y_nodes = norm_y.(y_raw)
b_nodes = norm_z.(b_raw)

wx = norm_x.(wx_raw)
wy = norm_y.(wy_raw)
wb = norm_z.(wb_raw)
water_h = Float32.(water_h_raw .* scene_scale)

WATER_DEPTH_THRESHOLD = Float32(0.5 * scene_scale)

# Per-vertex colors from elevation via colormap.
# :greenbrownterrain starts at pure black, so skip the dark/white extremes.
cmap_full = Makie.resample_cmap(:greenbrownterrain, 256)
cmap = cmap_full[30:250]
n_cmap = length(cmap)

b_lo, b_hi = extrema(b_nodes)
terrain_colors = map(b_nodes) do b
    t = clamp((b - b_lo) / (b_hi - b_lo), 0f0, 1f0)
    idx = clamp(round(Int, t * (n_cmap - 1)) + 1, 1, n_cmap)
    RGBAf(cmap[idx])
end

# Build terrain mesh
bathy_points = [Point3f(x_nodes[i], y_nodes[i], b_nodes[i]) for i in eachindex(x_nodes)]
gb_faces = [GLTriangleFace(terrain_faces[i, 1], terrain_faces[i, 2], terrain_faces[i, 3])
            for i in axes(terrain_faces, 1)]

# Build figure with SunSkyLight
fig = Figure(size=(1400, 900))
ax = LScene(fig[1:4, 1:3])

sun_sky = SunSkyLight(Vec3f(0.4, 0.3, 0.8);
    intensity=1.0f0,
    turbidity=2.5f0,
    ground_enabled=false)
push_light!(ax.scene, sun_sky)

# Bathymetry with per-vertex colors
mesh!(ax, bathy_points, gb_faces; color=terrain_colors)

# Water: transparent dielectric (IOR 1.33, slight blue tint via transmittance)
water_material = Hikari.Dielectric(
    Kt=(0.7, 0.85, 0.95),
    index=1.33f0,
    roughness=0.000f0)

# Top surface faces only (indices 1..n_water)
top_face_mask = [water_faces[i, 1] <= n_water && water_faces[i, 2] <= n_water && water_faces[i, 3] <= n_water
                 for i in axes(water_faces, 1)]
water_top_tri = water_faces[top_face_mask, :]

# Precompute per-frame wet face masks and compact meshes.
# Only faces where ALL 3 vertices have depth > threshold are included.
frame_idx = Observable(20)

water_mesh = @lift begin
    h = water_h[:, $frame_idx]
    wet = h .> WATER_DEPTH_THRESHOLD

    # Filter to only fully-wet faces
    wet_rows = [wet[water_top_tri[i, 1]] && wet[water_top_tri[i, 2]] && wet[water_top_tri[i, 3]]
                for i in axes(water_top_tri, 1)]
    active_tri = water_top_tri[wet_rows, :]

    # Compact: collect only referenced vertices
    used = falses(n_water)
    for i in axes(active_tri, 1), j in 1:3
        used[active_tri[i, j]] = true
    end
    old_to_new = zeros(Int32, n_water)
    new_count = Int32(0)
    for i in 1:n_water
        if used[i]
            new_count += 1
            old_to_new[i] = new_count
        end
    end

    # Build compact points and faces
    pts = Vector{Point3f}(undef, new_count)
    for i in 1:n_water
        used[i] || continue
        pts[old_to_new[i]] = Point3f(wx[i], wy[i], wb[i] + h[i])
    end
    faces = [GLTriangleFace(old_to_new[active_tri[i, 1]], old_to_new[active_tri[i, 2]],
        old_to_new[active_tri[i, 3]]) for i in axes(active_tri, 1)]
    GeometryBasics.normal_mesh(GeometryBasics.Mesh(pts, faces))
end

mesh!(ax, water_mesh;
    color=RGBAf(0.7, 0.85, 0.95, 0.8),
    material=water_material)

# Controls
sl = Makie.Slider(fig[5, 1:2], range=1:n_frames, startvalue=1)
set_close_to!(sl, 20)

connect!(frame_idx, sl.value)

play_btn = Makie.Button(fig[5, 3], label="Play")
time_label = @lift "t = $(round(times[$frame_idx], digits=1))s"
Label(fig[6, 1:3], time_label, fontsize=18)

# Play/Pause logic
is_playing = Observable(false)
on(play_btn.clicks) do _
    is_playing[] = !is_playing[]
    if is_playing[]
        play_btn.label = "Pause"
        @async begin
            while is_playing[]
                current = sl.value[]
                if current >= n_frames
                    is_playing[] = false
                    play_btn.label = "Play"
                    break
                end
                set_close_to!(sl, current + 1)
                sleep(0.15)
            end
        end
    else
        play_btn.label = "Play"
    end
end

Makie.update_state_before_display!(fig)
sensor = Hikari.FilmSensor(iso=10, white_balance=6500)
RayMakie.vulkan_viewer(fig; sensor=sensor)
